version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass password
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

  app:
    build: .
    command: sh docker-launch.sh
    ports:
      - '5000:5000'
    environment:
      - REDIS_URL=redis://:password@redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    build: .
    command: celery flower --broker=redis://:password@redis:6379/0
    ports:
      - '5555:5555'
    depends_on:
      - redis

volumes:
  redis: